---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project


# To run
#   * Ensure Docker is installed and running
#   * Start Egeria Platform stack using
#     'coco-lab-docker-compose -f ./egeria-platform-postgres.yaml up'
#
# Assumptions:
#   * Ports 9443 and 9092 are available on the host system - these are the default ports for Kafka and Egeria.
#   * by default, no external volumes are used - comments below give examples of using external volumes
#   * by default, Egeria will start with its set of default servers (active-metadata-store,view-server,
#     integration-daemon,engine-host,simple-metadata-store) - you can change this.
#   * by default, strict SSL validation is turned off
#
# See the following link for more info on volumes & why we need to use root:
#   https://docs.bitnami.com/containers/how-to/work-with-non-root-containers

services:
    jupyter-hub:
        depends_on:
            egeria-core:
                condition: service_healthy
            egeria-datalake:
                condition: service_healthy
            egeria-dev:
                condition: service_healthy

        image: quay.io/jupyter/minimal-notebook
        container_name: jupyter
        ports:
            - 8888:8888
        environment:
            JUPYTER_ENABLE_LAB: "yes"
            JUPYTER_TOKEN: "egeria"
        build:
            dockerfile: Dockerfile

        volumes:
            - ../coco-jupyter-labs/:/home/jovyan/work
            - ./before-notebook.d:/usr/local/bin/before-notebook.d
            - ./coco-lab-docker-compose:/home/jovyan/scripts

    kafka:
         image: 'bitnami/kafka:latest'
         ports:
             - '9192:9192'

         environment:
             - KAFKA_CFG_NODE_ID=0
             - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
             - KAFKA_CFG_PROCESS_ROLES=controller,broker
             - KAFKA_CFG_LISTENERS=PLAINTEXT://:9192,CONTROLLER://:9193
             - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
             - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9193
             - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

    egeria-core:
        depends_on:
            - kafka
        image: 'docker.io/odpi/egeria-platform:latest'
        ports:
            - '9743:9743'

        environment:
            - XTDB_ENABLE_BYTEUTILS_SHA1=True
            - XTDB_DISABLE_LIBCRYPTO=True
            - startup.server.list=
            - server.port=9743
        healthcheck:
            test:  curl -k -X GET "https://localhost:9743/open-metadata/platform-services/users/garygeeke/server-platform/origin" || exit 1

        #        volumes:
        #            - "YOUR DATA DIRECTORY"/data:/deployments/data
        #            - "YOUR EXTRA LIBRARY DIRECTORY"/extra:/deployments/extra
        #            - "ANOTHER DIRECTOR TO MOUNT"/:/deployments/user_mount
    egeria-datalake:
        depends_on:
            - kafka

        image: 'docker.io/odpi/egeria-platform:latest'
        ports:
            - '9744:9744'

        environment:
            - XTDB_ENABLE_BYTEUTILS_SHA1=True
            - XTDB_DISABLE_LIBCRYPTO=True
            - startup.server.list=
            - server.port=9744
        healthcheck:
            test: curl -k -X GET "https://localhost:9744/open-metadata/platform-services/users/garygeeke/server-platform/origin" || exit 1

    egeria-dev:
        depends_on:
            - kafka

        image: 'docker.io/odpi/egeria-platform:latest'
        ports:
            - '9745:9745'

        environment:
            - XTDB_ENABLE_BYTEUTILS_SHA1=True
            - XTDB_DISABLE_LIBCRYPTO=True
            - startup.server.list=
            - server.port=9745
        healthcheck:
            test: curl -k -X GET "https://localhost:9745/open-metadata/platform-services/users/garygeeke/server-platform/origin" || exit 1



#    postgres:
#        image: postgres:latest
#        container_name: observations
#        restart: always
#        ports:
#            - "127.0.0.1:5432:5432"
#
#        shm_size: 128mb
#        environment:
#            POSTGRES_PASSWORD: notingres
#        volumes:
#            - db_home:/var/lib/postgresql/data
#            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d


#
# Change external to true and create volumes manually if you wish to persist between runs
#
volumes:
    zookeeper-data:
        external: false
    kafka-data:
        external: false
    db_home:
        external: false
